dataset:
    name:
    train_roots:
        - /raid/lilong/data/face/face_recog/
        # - /raid/lilong/data/face/digiface_mxrecord/
    val_roots:
        - /raid/lilong/data/face/face_recog/agedb_30.bin
        - /mnt/nas/public2/yinanzhou/face_recognition/datasets/adv_1000/adv_1000.bin
    train_probs: null
    balanced: False
    img_aug_p: 0.1
    normalize: False
    in_channel: RGB
    output_shape: [112,112]

loss:
    name: cosface
    s: 64
    m: 0.5

optimizer:
    lr: 0.01
    weight_decay: 0.00005
    momentum: 0.9
    warmup_epoch: 0

network:
    name: iresnet100
    dropout: 0
    num_features: 512
    pretrained: /mnt/nas/public2/lilong/repos/arcface/ckpt/face_recog_exp/date:04-03-2023_Time:08:59_loss_9.7817__step208000_backbone.pth
    pretrained_prefix: ""

training:
    tensorboard_log_dir: logs/
    checkpoint_path: ckpt/
    best_pth_path: best_model_path.txt
    onnx_path: 'model.onnx'
    # experiment_name: face_recog_exp_webface_digi
    experiment_name: face_recog_exp
    epoch: 20
    precision: 16
    val_check_interval: 4000
    start_validation_step: 4000
    train_batch_size: 160
    val_batch_size: 512
    num_workers: 4
    syncbatchnorm: True
    log_every_n_steps: 100
    warmup: 0
    freeze_keys: null # ['fc','features'] #['layer4','bn2','fc','features'] #null #
    sample_rate: 0.2

onnx:
    input_names:
        - 'input_image'
    input_shapes:
        - [1, 3, 112, 112]
    dtypes:
        - float
    opset_version: 11
